export const GET_VERIFIED_USER_DATA = 'GET_VERIFIED_USER_DATA';
export const VERID_VERIFIED_USER_DATA = 'VERID_VERIFIED_USER_DATA';
export const VERID_USER_DATA = 'VERID_USER_DATA';
export const GET_VERIFIED_VERID_USER_DATA = 'GET_VERIFIED_VERID_USER_DATA';
